# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0002_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listened',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
