# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0003_song_listened'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.ManyToManyField(default=1, related_name='rating_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='listened',
            field=models.ManyToManyField(default=1, related_name='listened_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
