# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0005_auto_20160810_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='song',
        ),
        migrations.AddField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='song_star', to='player.Song'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='song_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
